markdown:       rdiscount
highlighter:    true
permalink:      ./:title
name:           Perfection Kills
description:    "Javascript rants and findings, by kangax"
url:            http://perfectionkills.com
encoding:       UTF-8

exclude:        ["README"]
sass:
  style:        compressed
